version: "3"
services:
  ftps:
    image: ngeor/vsftpd
    environment:
      PASSWORD: pass
    volumes:
      - ./ftp-srv:/home/files
    ports:
      - "990:990"
      - "10090-10100:10090-10100"
    command: sh /docker-entrypoint.sh
